const languages = {
    en: {
        languageName: "English",
        languageEnglish: "English",
        languageSpanish: "Spanish",
        languageFrench: "French",
        languageGerman: "German",
        languageChinese: "Chinese",
        appName: "Pill Reminder",
        home: "Home",
        homeTitle: "Pill Reminder",
        morning: "Morning",
        afternoon: "Afternoon",
        evening: "Evening",
        addMedicine: "Add Medicine",
        medicineName: "Medicine Name",
        time: "Time",
        taken: "TAKEN",
        missed: "MISSED",
        noMedications: "No medications scheduled",
        settings: "Settings",
        language: "Language",
        save: "Save",
        close: "Close",
        alertEnterMedicine: "Please enter a medicine name",
        alertSelectTime: "Please select a time",
        alertAdded: "{name} added to {timeOfDay} medications",
        alertStatus: "{name} marked as {status}",
        alertRemoved: "{name} removed from {timeOfDay} medications",
        footer: "2025 Pill Reminder. All rights reserved.",
        recordsTitle: "Medication Records",
        selectDate: "Select Date",
        noRecords: "No records for {date}",
        editRecord: "Edit record",
        deleteRecord: "Delete record",
        recordUpdated: "Record updated successfully!",
        recordDeleted: "Record deleted successfully!",
        confirmDelete: "Are you sure you want to delete {name}?",
        account: "Account",
        accountTitle: "Account - Pill Reminder",
        accountManagement: "Account Management",
        accountAuthentication: "Account Authentication",
        username: "Username",
        password: "Password",
        signIn: "Sign In",
        register: "Register",
        welcomeUser: "Welcome, {user}",
        welcomeBack: "Welcome back, {user}! You are now logged in.",
        signOut: "Sign Out",
        enterUsernamePassword: "Please enter both username and password.",
        usernameNotFound: "Username not found. Please register first.",
        incorrectPassword: "Incorrect password. Please try again.",
        passwordTooShort: "Password must be at least 6 characters long.",
        usernameExists: "Username already exists. Please choose another.",
        accountCreated: "Account created successfully! You are now logged in.",
        passwordManagement: "Password Management",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmPassword: "Confirm New Password",
        changePassword: "Change Password",
        fillPasswordFields: "Please fill in all password fields.",
        passwordsNotMatch: "New passwords do not match.",
        incorrectCurrentPassword: "Current password is incorrect.",
        passwordChanged: "Password changed successfully!",
        dataManagement: "Data Management",
        backupData: "Backup Data",
        clearData: "Clear All Data",
        signInToBackup: "Please sign in to backup your data.",
        signInToClear: "Please sign in to clear your data.",
        confirmClearData: "Are you sure you want to clear all data? This cannot be undone.",
        dataBackedUp: "Your data has been backed up successfully!",
        dataCleared: "All data has been cleared successfully.",
        support: "Support",
        askQuestion: "Ask a question...",
        submitQuestion: "Submit Question",
        enterQuestion: "Please enter your question.",
        questionSubmitted: "Your question has been submitted. We will respond soon.",
        feedback: "Feedback",
        yourFeedback: "Your feedback...",
        submitFeedback: "Submit Feedback",
        enterFeedback: "Please enter your feedback.",
        feedbackSubmitted: "Thank you for your feedback!",
        invalidUsername: "Username can only contain letters, numbers, and underscores."
    },
    es: {
        languageName: "Español",
        languageEnglish: "Inglés",
        languageSpanish: "Español",
        languageFrench: "Francés",
        languageGerman: "Alemán",
        languageChinese: "Chino",
        appName: "Recordatorio de Pastillas",
        home: "Inicio",
        homeTitle: "Recordatorio de Pastillas",
        morning: "Mañana",
        afternoon: "Tarde",
        evening: "Noche",
        addMedicine: "Agregar Medicamento",
        medicineName: "Nombre del Medicamento",
        time: "Hora",
        taken: "TOMADO",
        missed: "PERDIDO",
        noMedications: "No hay medicamentos programados",
        settings: "Configuraciones",
        language: "Idioma",
        save: "Guardar",
        close: "Cerrar",
        alertEnterMedicine: "Por favor, ingrese el nombre del medicamento",
        alertSelectTime: "Por favor, seleccione una hora",
        alertAdded: "{name} agregado a los medicamentos de {timeOfDay}",
        alertStatus: "{name} marcado como {status}",
        alertRemoved: "{name} eliminado de los medicamentos de {timeOfDay}",
        footer: "2025 Recordatorio de Pastillas. Todos los derechos reservados.",
        recordsTitle: "Registros de Medicamentos",
        selectDate: "Seleccionar Fecha",
        noRecords: "No hay registros para {date}",
        editRecord: "Editar registro",
        deleteRecord: "Eliminar registro",
        recordUpdated: "¡Registro actualizado exitosamente!",
        recordDeleted: "¡Registro eliminado exitosamente!",
        confirmDelete: "¿Estás seguro de que quieres eliminar {name}?",
        account: "Cuenta",
        accountTitle: "Cuenta - Recordatorio de Pastillas",
        accountManagement: "Gestión de Cuenta",
        accountAuthentication: "Autenticación de Cuenta",
        username: "Nombre de usuario",
        password: "Contraseña",
        signIn: "Iniciar Sesión",
        register: "Registrarse",
        welcomeUser: "Bienvenido, {user}",
        welcomeBack: "¡Bienvenido de nuevo, {user}! Has iniciado sesión.",
        signOut: "Cerrar Sesión",
        enterUsernamePassword: "Por favor, ingrese nombre de usuario y contraseña.",
        usernameNotFound: "Nombre de usuario no encontrado. Regístrese primero.",
        incorrectPassword: "Contraseña incorrecta. Inténtalo de nuevo.",
        passwordTooShort: "La contraseña debe tener al menos 6 caracteres.",
        usernameExists: "El nombre de usuario ya existe. Elija otro.",
        accountCreated: "¡Cuenta creada exitosamente! Has iniciado sesión.",
        passwordManagement: "Gestión de Contraseña",
        currentPassword: "Contraseña Actual",
        newPassword: "Nueva Contraseña",
        confirmPassword: "Confirmar Nueva Contraseña",
        changePassword: "Cambiar Contraseña",
        fillPasswordFields: "Por favor, complete todos los campos de contraseña.",
        passwordsNotMatch: "Las nuevas contraseñas no coinciden.",
        incorrectCurrentPassword: "La contraseña actual es incorrecta.",
        passwordChanged: "¡Contraseña cambiada exitosamente!",
        dataManagement: "Gestión de Datos",
        backupData: "Respaldar Datos",
        clearData: "Borrar Todos los Datos",
        signInToBackup: "Por favor, inicie sesión para respaldar sus datos.",
        signInToClear: "Por favor, inicie sesión para borrar sus datos.",
        confirmClearData: "¿Estás seguro de que quieres borrar todos los datos? Esto no se puede deshacer.",
        dataBackedUp: "¡Tus datos han sido respaldados exitosamente!",
        dataCleared: "¡Todos los datos han sido borrados exitosamente!",
        support: "Soporte",
        askQuestion: "Haga una pregunta...",
        submitQuestion: "Enviar Pregunta",
        enterQuestion: "Por favor, ingrese su pregunta.",
        questionSubmitted: "Su pregunta ha sido enviada. Responderemos pronto.",
        feedback: "Comentarios",
        yourFeedback: "Sus comentarios...",
        submitFeedback: "Enviar Comentarios",
        enterFeedback: "Por favor, ingrese sus comentarios.",
        feedbackSubmitted: "¡Gracias por tus comentarios!",
        invalidUsername: "El nombre de usuario solo puede contener letras, números y guiones bajos."
    },
    fr: {
        languageName: "Français",
        languageEnglish: "Anglais",
        languageSpanish: "Espagnol",
        languageFrench: "Français",
        languageGerman: "Allemand",
        languageChinese: "Chinois",
        appName: "Rappel de Médicaments",
        home: "Accueil",
        homeTitle: "Rappel de Médicaments",
        morning: "Matin",
        afternoon: "Après-midi",
        evening: "Soir",
        addMedicine: "Ajouter un Médicament",
        medicineName: "Nom du Médicament",
        time: "Heure",
        taken: "PRIS",
        missed: "MANQUÉ",
        noMedications: "Aucun médicament programmé",
        settings: "Paramètres",
        language: "Langue",
        save: "Enregistrer",
        close: "Fermer",
        alertEnterMedicine: "Veuillez entrer le nom du médicament",
        alertSelectTime: "Veuillez sélectionner une heure",
        alertAdded: "{name} ajouté aux médicaments de {timeOfDay}",
        alertStatus: "{name} marqué comme {status}",
        alertRemoved: "{name} supprimé des médicaments de {timeOfDay}",
        footer: "2025 Rappel de Médicaments. Tous droits réservés.",
        recordsTitle: "Registres des Médicaments",
        selectDate: "Sélectionner une Date",
        noRecords: "Aucun registre pour {date}",
        editRecord: "Modifier le registre",
        deleteRecord: "Supprimer le registre",
        recordUpdated: "Registre mis à jour avec succès !",
        recordDeleted: "Registre supprimé avec succès !",
        confirmDelete: "Êtes-vous sûr de vouloir supprimer {name} ?",
        account: "Compte",
        accountTitle: "Compte - Rappel de Médicaments",
        accountManagement: "Gestion de Compte",
        accountAuthentication: "Authentification de Compte",
        username: "Nom d'utilisateur",
        password: "Mot de passe",
        signIn: "Se Connecter",
        register: "S'inscrire",
        welcomeUser: "Bienvenue, {user}",
        welcomeBack: "Bon retour, {user} ! Vous êtes connecté.",
        signOut: "Se Déconnecter",
        enterUsernamePassword: "Veuillez entrer un nom d'utilisateur et un mot de passe.",
        usernameNotFound: "Nom d'utilisateur non trouvé. Inscrivez-vous d'abord.",
        incorrectPassword: "Mot de passe incorrect. Réessayez.",
        passwordTooShort: "Le mot de passe doit comporter au moins 6 caractères.",
        usernameExists: "Ce nom d'utilisateur existe déjà. Choisissez-en un autre.",
        accountCreated: "Compte créé avec succès ! Vous êtes connecté.",
        passwordManagement: "Gestion du Mot de Passe",
        currentPassword: "Mot de Passe Actuel",
        newPassword: "Nouveau Mot de Passe",
        confirmPassword: "Confirmer le Nouveau Mot de Passe",
        changePassword: "Changer le Mot de Passe",
        fillPasswordFields: "Veuillez remplir tous les champs de mot de passe.",
        passwordsNotMatch: "Les nouveaux mots de passe ne correspondent pas.",
        incorrectCurrentPassword: "Le mot de passe actuel est incorrect.",
        passwordChanged: "Mot de passe changé avec succès !",
        dataManagement: "Gestion des Données",
        backupData: "Sauvegarder les Données",
        clearData: "Supprimer Toutes les Données",
        signInToBackup: "Veuillez vous connecter pour sauvegarder vos données.",
        signInToClear: "Veuillez vous connecter pour supprimer vos données.",
        confirmClearData: "Êtes-vous sûr de vouloir supprimer toutes les données ? Cela ne peut pas être annulé.",
        dataBackedUp: "Vos données ont été sauvegardées avec succès !",
        dataCleared: "Toutes les données ont été supprimées avec succès !",
        support: "Support",
        askQuestion: "Posez une question...",
        submitQuestion: "Soumettre la Question",
        enterQuestion: "Veuillez entrer votre question.",
        questionSubmitted: "Votre question a été soumise. Nous répondrons bientôt.",
        feedback: "Commentaires",
        yourFeedback: "Vos commentaires...",
        submitFeedback: "Soumettre les Commentaires",
        enterFeedback: "Veuillez entrer vos commentaires.",
        feedbackSubmitted: "Merci pour vos commentaires !",
        invalidUsername: "Le nom d'utilisateur ne peut contenir que des lettres, des chiffres et des tirets bas."
    },
    de: {
        languageName: "Deutsch",
        languageEnglish: "Englisch",
        languageSpanish: "Spanisch",
        languageFrench: "Französisch",
        languageGerman: "Deutsch",
        languageChinese: "Chinesisch",
        appName: "Medikamentenerinnerung",
        home: "Startseite",
        homeTitle: "Medikamentenerinnerung",
        morning: "Morgen",
        afternoon: "Nachmittag",
        evening: "Abend",
        addMedicine: "Medikament Hinzufügen",
        medicineName: "Medikamentenname",
        time: "Zeit",
        taken: "GENOMMEN",
        missed: "VERPASST",
        noMedications: "Keine Medikamente geplant",
        settings: "Einstellungen",
        language: "Sprache",
        save: "Speichern",
        close: "Schließen",
        alertEnterMedicine: "Bitte geben Sie den Namen des Medikaments ein",
        alertSelectTime: "Bitte wählen Sie eine Zeit aus",
        alertAdded: "{name} zu den Medikamenten von {timeOfDay} hinzugefügt",
        alertStatus: "{name} als {status} markiert",
        alertRemoved: "{name} aus den Medikamenten von {timeOfDay} entfernt",
        footer: "2025 Medikamentenerinnerung. Alle Rechte vorbehalten.",
        recordsTitle: "Medikamentenaufzeichnungen",
        selectDate: "Datum Auswählen",
        noRecords: "Keine Aufzeichnungen für {date}",
        editRecord: "Aufzeichnung bearbeiten",
        deleteRecord: "Aufzeichnung löschen",
        recordUpdated: "Aufzeichnung erfolgreich aktualisiert!",
        recordDeleted: "Aufzeichnung erfolgreich gelöscht!",
        confirmDelete: "Sind Sie sicher, dass Sie {name} löschen möchten?",
        account: "Konto",
        accountTitle: "Konto - Medikamentenerinnerung",
        accountManagement: "Kontenverwaltung",
        accountAuthentication: "Kontoauthentifizierung",
        username: "Benutzername",
        password: "Passwort",
        signIn: "Anmelden",
        register: "Registrieren",
        welcomeUser: "Willkommen, {user}",
        welcomeBack: "Willkommen zurück, {user}! Sie sind jetzt angemeldet.",
        signOut: "Abmelden",
        enterUsernamePassword: "Bitte geben Sie Benutzername und Passwort ein.",
        usernameNotFound: "Benutzername nicht gefunden. Bitte registrieren Sie sich zuerst.",
        incorrectPassword: "Falsches Passwort. Bitte versuchen Sie es erneut.",
        passwordTooShort: "Das Passwort muss mindestens 6 Zeichen lang sein.",
        usernameExists: "Benutzername existiert bereits. Bitte wählen Sie einen anderen.",
        accountCreated: "Konto erfolgreich erstellt! Sie sind jetzt angemeldet.",
        passwordManagement: "Passwortverwaltung",
        currentPassword: "Aktuelles Passwort",
        newPassword: "Neues Passwort",
        confirmPassword: "Neues Passwort bestätigen",
        changePassword: "Passwort ändern",
        fillPasswordFields: "Bitte füllen Sie alle Passwortfelder aus.",
        passwordsNotMatch: "Die neuen Passwörter stimmen nicht überein.",
        incorrectCurrentPassword: "Das aktuelle Passwort ist falsch.",
        passwordChanged: "Passwort erfolgreich geändert!",
        dataManagement: "Datenverwaltung",
        backupData: "Daten sichern",
        clearData: "Alle Daten löschen",
        signInToBackup: "Bitte melden Sie sich an, um Ihre Daten zu sichern.",
        signInToClear: "Bitte melden Sie sich an, um Ihre Daten zu löschen.",
        confirmClearData: "Sind Sie sicher, dass Sie alle Daten löschen möchten? Dies kann nicht rückgängig gemacht werden.",
        dataBackedUp: "Ihre Daten wurden erfolgreich gesichert!",
        dataCleared: "Alle Daten wurden erfolgreich gelöscht!",
        support: "Support",
        askQuestion: "Stellen Sie eine Frage...",
        submitQuestion: "Frage einreichen",
        enterQuestion: "Bitte geben Sie Ihre Frage ein.",
        questionSubmitted: "Ihre Frage wurde eingereicht. Wir werden bald antworten.",
        feedback: "Feedback",
        yourFeedback: "Ihr Feedback...",
        submitFeedback: "Feedback senden",
        enterFeedback: "Bitte geben Sie Ihr Feedback ein.",
        feedbackSubmitted: "Vielen Dank für Ihr Feedback!",
        invalidUsername: "Der Benutzername darf nur Buchstaben, Zahlen und Unterstriche enthalten."
    },
    zh: {
        languageName: "中文",
        languageEnglish: "英语",
        languageSpanish: "西班牙语",
        languageFrench: "法语",
        languageGerman: "德语",
        languageChinese: "中文",
        appName: "药物提醒",
        home: "主页",
        homeTitle: "药物提醒",
        morning: "早上",
        afternoon: "下午",
        evening: "晚上",
        addMedicine: "添加药物",
        medicineName: "药物名称",
        time: "时间",
        taken: "已服用",
        missed: "未服用",
        noMedications: "没有安排的药物",
        settings: "设置",
        language: "语言",
        save: "保存",
        close: "关闭",
        alertEnterMedicine: "请输入药物名称",
        alertSelectTime: "请选择时间",
        alertAdded: "{name} 已添加到 {timeOfDay} 的药物中",
        alertStatus: "{name} 被标记为 {status}",
        alertRemoved: "{name} 已从 {timeOfDay} 的药物中移除",
        footer: "2025 药物提醒。保留所有权利。",
        recordsTitle: "药物记录",
        selectDate: "选择日期",
        noRecords: "{date} 没有记录",
        editRecord: "编辑记录",
        deleteRecord: "删除记录",
        recordUpdated: "记录更新成功！",
        recordDeleted: "记录删除成功！",
        confirmDelete: "您确定要删除 {name} 吗？",
        account: "账户",
        accountTitle: "账户 - 药物提醒",
        accountManagement: "账户管理",
        accountAuthentication: "账户认证",
        username: "用户名",
        password: "密码",
        signIn: "登录",
        register: "注册",
        welcomeUser: "欢迎，{user}",
        welcomeBack: "欢迎回来，{user}！您已登录。",
        signOut: "退出登录",
        enterUsernamePassword: "请输入用户名和密码。",
        usernameNotFound: "用户名未找到。请先注册。",
        incorrectPassword: "密码错误。请重试。",
        passwordTooShort: "密码必须至少6个字符。",
        usernameExists: "用户名已存在。请另选一个。",
        accountCreated: "账户创建成功！您已登录。",
        passwordManagement: "密码管理",
        currentPassword: "当前密码",
        newPassword: "新密码",
        confirmPassword: "确认新密码",
        changePassword: "更改密码",
        fillPasswordFields: "请填写所有密码字段。",
        passwordsNotMatch: "新密码不匹配。",
        incorrectCurrentPassword: "当前密码不正确。",
        passwordChanged: "密码更改成功！",
        dataManagement: "数据管理",
        backupData: "备份数据",
        clearData: "清除所有数据",
        signInToBackup: "请登录以备份您的数据。",
        signInToClear: "请登录以清除您的数据。",
        confirmClearData: "您确定要清除所有数据吗？此操作无法撤销。",
        dataBackedUp: "您的数据已成功备份！",
        dataCleared: "所有数据已成功清除！",
        support: "支持",
        askQuestion: "提出问题...",
        submitQuestion: "提交问题",
        enterQuestion: "请输入您的问题。",
        questionSubmitted: "您的问题已提交。我们将尽快回复。",
        feedback: "反馈",
        yourFeedback: "您的反馈...",
        submitFeedback: "提交反馈",
        enterFeedback: "请输入您的反馈。",
        feedbackSubmitted: "感谢您的反馈！",
        invalidUsername: "用户名只能包含字母、数字和下划线。"
    }
};

function getCurrentLanguage() {
    return localStorage.getItem('appLanguage') || 'en';
}

function setLanguage(lang) {
    if (languages[lang]) {
        localStorage.setItem('appLanguage', lang);
        updateUIText();
    }
}

function updateUIText() {
    const lang = getCurrentLanguage();
    const translations = languages[lang];
    
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');
        if (translations[key]) {
            if (element.hasAttribute('data-i18n-placeholder')) {
                element.placeholder = translations[key];
            } else {
                element.textContent = translations[key];
            }
        }
    });
    
    document.querySelectorAll('.empty-state p').forEach(p => {
        if (p.closest('#morningList') || p.closest('#afternoonList') || p.closest('#eveningList')) {
            p.textContent = translations.noMedications;
        } else if (p.closest('#recorded-list')) {
            p.textContent = translations.noRecords.replace('{date}', formatDisplayDate(document.getElementById('select-date')?.value || formatDate(new Date())));
        }
    });
    
    const footer = document.querySelector('footer .bi-c-circle')?.nextElementSibling;
    if (footer) {
        footer.textContent = ` ${new Date().getFullYear()} ${translations.footer}`;
    }
}

function formatDate(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

function formatDisplayDate(dateStr) {
    const options = { year: 'numeric', month: 'long', day: 'numeric' };
    return new Date(dateStr).toLocaleDateString(getCurrentLanguage(), options);
}